### ISSUE TITLE
windows defender

### ISSUE THREAD

**Issue by LETSQ000** [TOPexecutors-windows/TOPexecutors-windows#1]
windows defender blocks it is it dangerus for my computer?

**Comment by TOPexecutors-windows** [comment]
> windows defender blocks it is it dangerus for my computer?

No its completley normal every single executor gets blocked. i hope this helps thank you for using JJsploit v2

**Comment by LETSQ000** [comment]
what do i do every time i press it just gets blocked

**Comment by TOPexecutors-windows** [comment]
> s



> what do i do every time i press it just gets blocked

when it pops up and says it got blocked press more then run anyway then it should work. hope this helps
